# Generated by Django 6.0.7 on 2026-09-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
