# Generated by Django 6.0.7 on 2026-09-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_tag_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='object_id',
        ),
    ]
